In [34]:
# modules for different random numbers generation
#pseudo random numbers
import random

a = random.random()
print(a)

0.09158478740507359


In [35]:
import random

a = random.uniform(1,10)
print(a)


4.2495172658524645


In [3]:
import random

a = random.randint(1,10)
print(a)


9


In [4]:
import random

a = random.randrange(1,10)
print(a)


3


In [5]:
import random

a = random.normalvariate(0,1)
print(a)


-0.8544931600815944


In [7]:
import random

mylist = list("ABCDEFGH")
print(mylist)

a = random.choice(mylist)
print(a)


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
D


In [9]:
import random

mylist = list("ABCDEFGH")
print(mylist)

a = random.sample(mylist, 3)
print(a)


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['E', 'B', 'F']


In [12]:
import random

mylist = list("ABCDEFGH")
print(mylist)

a = random.choices(mylist, k=3)
print(a)


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['C', 'C', 'H']


In [13]:
import random

mylist = list("ABCDEFGH")
print(mylist)
random.shuffle(mylist)
print(mylist)


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['A', 'F', 'H', 'E', 'B', 'G', 'D', 'C']


In [18]:
#reproducing random numbers with random.seed
import random

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.13436424411240122
2
0.9560342718892494
1


In [20]:
import secrets

a = secrets.randbelow(10)
print(a)

b = secrets.randbits(4)
print(b)

mylist = list("ABCDEFG")
c = secrets.choice(mylist)
print(c)

8
15
D


In [22]:
import numpy as np

a = np.random.rand(3)
print(a)

[0.20844157 0.19463618 0.1536655 ]


In [23]:
import numpy as np

a = np.random.rand(3,3)
print(a)

[[0.26145831 0.47348737 0.36335655]
 [0.87778104 0.22738528 0.04519838]
 [0.16999541 0.46239788 0.56965224]]


In [24]:
import numpy as np

a = np.random.randint(0,10, 3)
print(a)

[6 2 6]


In [25]:
import numpy as np

a = np.random.randint(0,10,(3,4))
print(a)

[[4 8 2 3]
 [6 1 6 7]
 [5 3 6 2]]


In [30]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [33]:
import numpy as np

np.random.seed(1)
print(np.random.rand(3,3))

np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
